---
kinect_parameters:
  0: #parameters for the first Kinect
    stream_color_video: True
    stream_depth_video: True
    stream_ir_video: True
    streaming_color_format: "K4A_IMAGE_FORMAT_COLOR_BGRA32"
    streaming_color_resolution: "K4A_COLOR_RESOLUTION_720P"
    streaming_depth_mode: "K4A_DEPTH_MODE_NFOV_UNBINNED"
    wired_sync_mode: "K4A_WIRED_SYNC_MODE_STANDALONE"
    streaming_rate: "K4A_FRAMES_PER_SECOND_30"
    absoluteExposureValue: 0
video_encoder:
  0: #color
    type: "nvenc"
    codec_name: "NVPIPE_HEVC"
    input_format: "NVPIPE_RGBA32"
    bit_rate: 4000000
    width: 1280
    height: 720
  1: #depth
    type: "nvenc"
    codec_name: "NVPIPE_HEVC"
    input_format: "NVPIPE_UINT16"
    bit_rate: 15000000
    width: 640
    height: 576
  2: #ir
    type: "nvenc"
    codec_name: "NVPIPE_HEVC"
    input_format: "NVPIPE_UINT16"
    bit_rate: 15000000
    width: 640
    height: 576
  3: #ir
    type: "libav"
    codec_name: "png"
    pix_fmt: "gray16be"
    bit_rate: 8000000
    options:
      preset: "veryfast"
  4: #ir
    type: "libav"
    codec_name: "libx265"
    pix_fmt: "yuv420p"
    bit_rate: 15000000
    options:
      preset: "veryfast"