---
kinect_parameters:
  0: #parameters for the first Kinect
    stream_color_video: True
    stream_depth_video: True
    stream_ir_video: False
    streaming_color_format: "K4A_IMAGE_FORMAT_COLOR_MJPG"
    streaming_color_resolution: "K4A_COLOR_RESOLUTION_720P"
    streaming_depth_mode: "K4A_DEPTH_MODE_NFOV_UNBINNED"
    wired_sync_mode: "K4A_WIRED_SYNC_MODE_STANDALONE"
    streaming_rate: "K4A_FRAMES_PER_SECOND_30"
    absoluteExposureValue: 0
video_encoder:
  0: #color
    codec_name: "h264_nvenc"
    pix_fmt: "yuv420p"
    bit_rate: 8000000
    options:
      preset: "llhp"
      rc: "cbr_ld_hq"
  1: #depth
    codec_name: "libx265"
    pix_fmt: "gray12le"
    bit_rate: 8000000
    options:
      preset: "veryfast"
      crf: "23"
  2: #ir
    codec_name: "hevc_nvenc"
    pix_fmt: "yuv420p"
    bit_rate: 8000000
    options:
      preset: "ll"
      crf: "23"
