---
general:
  host: "localhost"
  port: 9999
  frame_source:
    type: "frames"
    parameters:
      path: "/home/amourao/code/2019-05_moetsi/davp-data-scripts/apt0-frames-depth.txt"
      path1: "/home/amourao/code/2019-05_moetsi/davp-data-scripts/stairs-seq-01-frames-depth.txt"
video_encoder:
  0: #color
    type: "libav"
    codec_name: "libx265"
    pix_fmt: "yuv420p"
    bit_rate: 4000000
    options:
      preset: "veryfast"
      crf: "23"
  1: #depth
    type: "zdepth"
    codec_name: "libx265"
    pix_fmt: "gray12le"
    bit_rate: 8000000
    options:
      preset: "veryfast"
      crf: "21"
    