---
general:
  host: "localhost"
  port: 9999
  log_level: "info"
  show_graphical_output: False
  frame_source:
    type: "video"
    parameters:
      path: "/home/amourao/output.mkv"
      streams: [1]
video_encoder:
  0: #color
    type: "nvenc"
    codec_name: "NVPIPE_HEVC"
    input_format: "NVPIPE_RGBA32"
    bit_rate: 4000000
  1: #depth
    type: "zdepth"
  2: #ir
    type: "nvenc"
    codec_name: "NVPIPE_HEVC"
    input_format: "NVPIPE_UINT16"
    bit_rate: 40000000
    