---
general:
  host: "localhost"
  port: 9999
  frame_source:
    type: "frames"
    parameters:
      path: "../examples/stairs-seq-01-frames-color.txt"
      path1: "../examples/stairs-seq-01-frames-depth.txt"
video_encoder:
  0: #color
    type: "libav"
    codec_name: "libx265"
    pix_fmt: "yuv420p"
    bit_rate: 4000000
    options:
      preset: "veryfast"
      crf: "23"
  1: #depth
    type: "zdepth"
    send_I_frame_interval: 30
    
