---
general:
  host: "localhost"
  port: 9999
  frame_source:
    type: "video"
    parameters:
      path: "/home/amourao/output2.mkv"
      streams: [0]
video_encoder:
  0: #color
    type: "nvenc"
    codec_name: "NVPIPE_HEVC"
    input_format: "NVPIPE_RGBA32"
    bit_rate: 4000000
  1: #depth
    type: "zdepth"
  2: #ir
    type: "zdepth"
    