---
general:
  host: "localhost"
  port: 9999
  frame_source:
    type: "frames"
    parameters:
      path: "/home/amourao/code/davp-data-scripts/stairs-seq-01-frames-color.txt"
video_encoder:
  0: #color
    type: "libav"
    codec_name: "libx265"
    pix_fmt: "yuv420p"
    bit_rate: 4000000
    options:
      preset: "veryfast"
      crf: "23"
  1: #depth
    type: "libav"
    codec_name: "libx265"
    pix_fmt: "gray12le"
    bit_rate: 8000000
    options:
      preset: "veryfast"
      crf: "23"
    